---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-python-1.0.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-python
      version: 1.0.0
      env: dev
      owner: maplelabs
  template:
    metadata:
      labels:
        app: hello-python
        version: 1.0.0
        env: dev
        owner: maplelabs
    spec:
      containers:
      - name: hello-python
        image: gmanal1005/hello-python:red
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
