---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: sample-app
  namespace: flux-system
spec:
  interval: 2m0s
  path: ./kustomize-app/python-app
  prune: true
  sourceRef:
    kind: GitRepository
    name: sample-app
  targetNamespace: test

